import { Context } from 'hono';
import { ContentfulStatusCode } from 'hono/utils/http-status';

import { config } from '../services/config.js';

/**
 * RFC 7807 Problem Details object structure.
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */
export type ProblemDetail = {
  /** A URI reference that identifies the problem type. */
  type: string;
  /** A short, human-readable summary of the problem type. */
  title: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status: ContentfulStatusCode;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
  [key: string]: any;
};

/**
 * Helper to construct a standardized RFC 7807 Response.
 *
 * @param c - The Hono Context.
 * @param status - HTTP Status Code.
 * @param type - Unique problem type identifier (suffix).
 * @param title - Human-readable title.
 * @param detail - Specific error details.
 * @param extras - Additional properties to include in the problem details.
 * @returns A JSON Response with 'application/problem+json' content type.
 */
export const createProblem = (
  c: Context,
  status: ContentfulStatusCode,
  type: string,
  title: string,
  detail?: string,
  extras?: Record<string, any>,
): Response => {
  const problem: ProblemDetail = {
    type: `${config.problemBaseUrl}/probs/${type}`,
    title,
    status,
    detail,
    instance: c.req.path,
    ...extras,
  };

  return c.json(problem, status, {
    'Content-Type': 'application/problem+json',
  });
};

export const problems = {
  badRequest: (c: Context, detail?: string) =>
    createProblem(c, 400, 'bad-request', 'Bad Request', detail),

  unauthorized: (
    c: Context,
    detail: string = 'Authentication credentials required or invalid',
  ) => createProblem(c, 401, 'unauthorized', 'Unauthorized', detail),

  forbidden: (c: Context, detail: string = 'Access denied') =>
    createProblem(c, 403, 'forbidden', 'Forbidden', detail),

  notFound: (c: Context, detail: string = 'Resource not found') =>
    createProblem(c, 404, 'not-found', 'Not Found', detail),

  rateLimited: (
    c: Context,
    detail: string = 'Rate limit exceeded',
    retryAfter?: number,
  ) => {
    const headers: Record<string, any> = {};
    if (retryAfter) {
      headers['Retry-After'] = retryAfter;
      c.header('Retry-After', String(retryAfter));
    }
    return createProblem(
      c,
      429,
      'rate-limited',
      'Rate Limit Exceeded',
      detail,
      headers,
    );
  },

  quotaExceeded: (c: Context, detail: string = 'Monthly quota exceeded') =>
    createProblem(c, 429, 'quota-exceeded', 'Quota Exceeded', detail),

  internalError: (
    c: Context,
    detail: string = 'An unexpected error occurred',
  ) =>
    createProblem(
      c,
      500,
      'internal-server-error',
      'Internal Server Error',
      detail,
    ),

  badGateway: (c: Context, detail: string = 'Upstream service failed') =>
    createProblem(c, 502, 'bad-gateway', 'Bad Gateway', detail),

  gatewayTimeout: (c: Context, detail: string = 'Upstream service timed out') =>
    createProblem(c, 504, 'gateway-timeout', 'Gateway Timeout', detail),
};
